### ISSUE TITLE
[MINOR] Email Report Type Bug

### ISSUE THREAD

**Issue by JovisCream** [SOFENGG-T1AY1617/S18A-Team-Ryan#17]
Pressing other types besides daily (Monthly, Term-End) and going back to DAILY drop-down ; daily displays the previous drop-down button.
 
![email send bug](https://cloud.githubusercontent.com/assets/17019541/21072327/2a646bc4-bef9-11e6-9db7-cad1e1a43f6b.gif)

**Comment by dnicanix** [comment]
Fixed
